Euler's Totient function, φ(n) [sometimes called the **_phi function_**], is used to determine the number of positive numbers less than or equal to n which are relatively prime to n. For example, as 1, 2, 4, 5, 7, and 8, are all less than nine and relatively prime to nine, φ(9)=6.
The number 1 is considered to be relatively prime to every positive number, so φ(1)=1.

Interestingly, φ(87109)=79180, and it can be seen that 87109 is a permutation of 79180.

Find the value of n, 1 < n < 10^7, for which φ(n) is a permutation of n and the ratio n/φ(n) produces a minimum.

#Approach:
##1. Calculate totients.
##2. If phi(n) is permutation of n, add to list
##3. Return n that has n/phi(n) minimum


In [1]:
import numpy as np
from fractions import Fraction
import eulertools
import itertools
import time

from collections import defaultdict, Counter

In [10]:
import cProfile

In [24]:
def phi(n, primes):
    '''phi(n) = n *prod(1-1/p)
    where the product is over the distinct prime numbers dividing n.'''
    factors = factorize(n, primes)
    tot = n
    for i in range(factors.shape[0]):
        if factors[i]:
            tot *= (1-1/primes[i])
    return int(tot)
            


def factorize(n,listofprimes):

    valueeachprime = np.zeros(len(listofprimes))
    for i in range(1, len(listofprimes)+1):
        while n >= listofprimes[i-1] and n % listofprimes[i-1] == 0:
            n = n / listofprimes[i-1]
            valueeachprime[i-1] = valueeachprime[i-1] + 1
    valueeachprime = valueeachprime[:i]
    return valueeachprime


def ret_z(lp): return np.zeros(len(lp))

def ret_n(n,lp, i): return n / lp[i-1]

def red_arr(arr, i): return arr[:i]

def factorize(n,listofprimes):

    valueeachprime = ret_z(listofprimes)
    for i in range(1, len(listofprimes)+1):
        while n >= listofprimes[i-1] and n % listofprimes[i-1] == 0:
            n = ret_n(n,listofprimes,i)
#            n = n / listofprimes[i-1]
            valueeachprime[i-1] = valueeachprime[i-1] + 1
    valueeachprime = red_arr(valueeachprime,i)
    return valueeachprime







def ispermutation(n, phi_n):
    n =str(n)
    phi_n = str(phi_n)
    
    if len(n) != len(phi_n):
        return False
    if set(n) != set(phi_n):
        return False
    cnt = Counter()
    
    for i in n:
        cnt[i] +=1
    for j in phi_n:
        cnt[j] -= 1
    sv = set(cnt.values())
    
    if len(sv) == 1 and 0 in sv:
        return True
    return False
    

In [38]:
target = 10000
primes = eulertools.primesfrom2to(target)

In [39]:
start = time.time()
cProfile.run('test()')
end = time.time()
print(end-start)

[21, 63, 291, 502, 2518, 2817, 2991, 4435, 5229, 5367, 5637, 6102, 6174, 6543, 6822, 7236, 7422, 8022, 8541, 8982]
         132818 function calls in 51.393 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     9998   12.425    0.001   51.070    0.005 <ipython-input-24-c9317c7cd3ab>:1(phi)
     9998    0.052    0.000    0.339    0.000 <ipython-input-24-c9317c7cd3ab>:24(ret_z)
    31977    0.140    0.000    0.140    0.000 <ipython-input-24-c9317c7cd3ab>:26(ret_n)
     9998    0.062    0.000    0.062    0.000 <ipython-input-24-c9317c7cd3ab>:28(red_arr)
     9998   38.097    0.004   38.646    0.004 <ipython-input-24-c9317c7cd3ab>:30(factorize)
     9998    0.205    0.000    0.224    0.000 <ipython-input-24-c9317c7cd3ab>:47(ispermutation)
        1    0.097    0.097   51.392   51.392 <ipython-input-7-478d98a27d2a>:1(test)
        1    0.000    0.000   51.392   51.392 <string>:1(<module>)
       89    0.006    0.000    0.007    0.

In [41]:
m = test()

In [40]:
def test():
    list_n = []
    list_phi_n = []

    for i in range(2,target):
        ph = phi(i, primes)
        if ispermutation(i, ph):
            list_n.append(i)
            list_phi_n.append(ph)
    return list_n

In [4]:
list_n = []
list_phi_n = []

for i in range(2,target):
    ph = phi(i, primes)
    if ispermutation(i, ph):
        list_n.append(i)
        list_phi_n.append(ph)


In [53]:
t = factorize(m[-2], primes)
print(m[-2])
for i in range(len(t)):
    
    if t[i]:
        
        print(i, '\t', t[i], primes[i])

8541
1 	 2.0 3
5 	 1.0 13
20 	 1.0 73


In [54]:
3*3*13*73

8541

In [44]:
for i in m:
    print(factorize(i, primes))

[ 0.  1.  0. ...,  0.  0.  0.]
[ 0.  2.  0. ...,  0.  0.  0.]
[ 0.  1.  0. ...,  0.  0.  0.]
[ 1.  0.  0. ...,  0.  0.  0.]
[ 1.  0.  0. ...,  0.  0.  0.]
[ 0.  2.  0. ...,  0.  0.  0.]
[ 0.  1.  0. ...,  0.  0.  0.]
[ 0.  0.  1. ...,  0.  0.  0.]
[ 0.  2.  0. ...,  0.  0.  0.]
[ 0.  1.  0. ...,  0.  0.  0.]
[ 0.  1.  0. ...,  0.  0.  0.]
[ 1.  3.  0. ...,  0.  0.  0.]
[ 1.  2.  0. ...,  0.  0.  0.]
[ 0.  2.  0. ...,  0.  0.  0.]
[ 1.  2.  0. ...,  0.  0.  0.]
[ 2.  3.  0. ...,  0.  0.  0.]
[ 1.  1.  0. ...,  0.  0.  0.]
[ 1.  1.  0. ...,  0.  0.  0.]
[ 0.  2.  0. ...,  0.  0.  0.]
[ 1.  2.  0. ...,  0.  0.  0.]


In [5]:
list_n

[21, 63]

In [52]:
len(list_n)

7

In [54]:
list_n, list_phi_n

([21, 63, 291, 502, 2518, 2817, 2991], [12, 36, 192, 250, 1258, 1872, 1992])

In [55]:
np.array(list_n) / np.array(list_phi_n)

array([ 1.75      ,  1.75      ,  1.515625  ,  2.008     ,  2.00158983,
        1.50480769,  1.50150602])

In [24]:
cnt = Counter()
for i in '1233':
    cnt[i] +=1
cnt

Counter({'3': 2, '2': 1, '1': 1})

In [25]:
for i in '1233':
    cnt[i] -=1
cnt

Counter({'2': 0, '3': 0, '1': 0})

In [33]:
len(set(cnt.values()))

1

In [38]:
0 in set(cnt.values())

True

In [46]:
ispermutation('avaccc','ccacva')

True

In [82]:
mult = 1
n = 0
while mult <target and n < len(primes):
    mult *= primes[n]
    n+=1
mult = mult / primes[n-1]
mult

510510.0

In [7]:
totient(9, eulertools.primesfrom2to(100))

6

In [83]:
### brute force attempts...

In [41]:
from scipy.sparse import lil_matrix
from scipy.sparse import csr_matrix

In [63]:
factors = np.ones((target,len(primes)), dtype= bool)
#factors
for i in range(0,len(factors)):
    factors[i] = factors[i] * factorize(i+1, primes)

In [64]:
start = time.time()
test = np.ones(factors.shape[0])
for i in range(factors.shape[0]):
    test[i] = ret_list_relative_primes(factors[:i], factors[i])
    
end = time.time()
print(end-start)

28.494981050491333


In [49]:
factors.shape

(1000, 168)

In [51]:
query = np.arange(1,factors.shape[0]+1)

In [55]:
test[27:30], query[27:30]

(array([ 12.,  28.,   8.]), array([28, 29, 30]))

In [57]:
30/8

3.75

In [52]:
np.argmax(query[1:]/test[1:])

208

In [53]:
max(query[1:]/test[1:])

4.375

In [54]:
factorize(np.argmax(query[1:]/test[1:]), eulertools.primesfrom2to(np.argmax(query[1:]/test[1:])))

array([ 4.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [61]:
tgt = 9699690
factorize(tgt, eulertools.primesfrom2to(100))

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [67]:
eulertools.primesfrom2to(100)

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97], dtype=int32)

In [72]:
mult/primes[n-1]

510510.0

In [151]:
factors = lil_matrix((target,len(primes)))

In [ ]:
for i in range(0,factors.shape[0]):
    factors[i] = csr_matrix(factorize(i+1, primes))

In [ ]:
start = time.time()

test = np.ones((factors.shape[0]))
for i in range(factors.shape[0]):
    test[i] = ret_list_relative_primes_sp(factors[:i], factors[i])

end = time.time()
print(end-start)


In [30]:
primes

array([  2,   3,   5,   7,  11,  13,  17,  19,  23,  29,  31,  37,  41,
        43,  47,  53,  59,  61,  67,  71,  73,  79,  83,  89,  97, 101,
       103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167,
       173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239,
       241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313,
       317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397,
       401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467,
       479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569,
       571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643,
       647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733,
       739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823,
       827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911,
       919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997], dtype=int32)

In [29]:
2*3*5*7*11

2310

In [31]:
mult = 1
n = 0
while mult <1000000 and n < len(primes):
    mult *= primes[n]
    n+=1

In [32]:
mult

9699690

In [54]:
query = np.arange(1,factors.shape[0]+1)

In [55]:
print(query.shape, test.shape)

(10,) (10,)


In [56]:
t = np.argmax(query[1:]/test[1:])
t

4

In [43]:
factors.toarray()[1].any()

True

In [12]:
query[t+1]

6

In [16]:
target = 1000

In [17]:
primes = eulertools.primesfrom2to(target)

In [18]:
value = np.zeros((target))
factors = defaultdict(int)
#factors
for i in range(1,target):
    for j in range(1,i):
        if np.any(factorize(i,primes) * factorize(j, primes)) == False:
            factors[i] += 1
            
for key in factors.keys():
    value[key] = key / factors[key]
        


KeyboardInterrupt: 

In [14]:
factors

defaultdict(<class 'int'>, {2: 1, 3: 2, 4: 2, 5: 4, 6: 2, 7: 6, 8: 4, 9: 6})

In [ ]:
np.argmax(value()