
Starting with 1 and spiralling anticlockwise in the following way, a square spiral with side length 7 is formed.


$$
|37| 36| 35| 34| 33| 32| 31| \\ 
|38| 17| 16| 15| 14| 13| 30|  \\
|39| 18|  5|  4|  3| 12| 29|  \\
|40| 19|  6|  1|  2| 11| 28|  \\
|41| 20|  7|  8|  9| 10| 27|  \\ 
|42| 21| 22| 23| 24| 25| 26| \\
|43| 44| 45| 46| 47| 48| 49|
$$


It is interesting to note that the odd squares lie along the bottom right diagonal, but what is more interesting is that 8 out of the 13 numbers lying along both diagonals are prime; that is, a ratio of 8/13 ≈ 62%.

If one complete new layer is wrapped around the spiral above, a square spiral with side length 9 will be formed. If this process is continued, what is the side length of the square spiral for which the ratio of primes along both diagonals first falls below 10%?

#Approach:
####1. Create matrix
####2. Fill matrix
####3. Check if diagonals are prime
####4. Calculate %

In [3]:
import numpy as np

In [4]:
def create_matrix(n):
    return np.zeros((n,n))

(2, 3, 1, 0)

In [65]:
def move(mat,position,direction):
    maxval = len(mat)
    minval = 0

    if direction == 'N':
        next_move = (-1,0)
    elif direction == 'E':
        next_move = (0,-1)
    elif direction == 'S':
        next_move = (1,0)
    elif direction == 'W':
        next_move = (0,1)
    else:
        raise ValueError('Only NWSE available as direction')
    new_position = (position[0]+next_move[0],position[1]+next_move[1])
    if minval < new_position[0] < maxval:
        if minval < new_position[1] <maxval:
            return new_position
    raise ValueError('Movement out of bounds')
        
    

In [70]:
move(a, (0,0), 'E')

ValueError: Movement out of bounds

In [58]:
def fill_matrix(mat):
    center = 1
    mat[np.floor(len(mat)/2)][np.floor(len(mat)/2)] = center
    vals = [x for x in range(1,len(mat)**2 +1)]
    for i in range(1,len(mat)+1,2):
        moves = 'W'  + (i-2)*'N' + (i-1)*'E' + (i-1)*'S' + (i-1)*'W'
        moves = list(moves)
        for move in moves:
            pass
            
    return  mat
        

In [59]:
a = create_matrix(3)

In [60]:
b =fill_matrix(a)

In [62]:
b[2][1]=3
b

array([[ 0.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  3.,  0.]])

In [24]:
b[0][0] = 11
b[1][1] = 1
b[2][2] = 2
b[3][3] = 3
b

array([[ 11.,   0.,   0.,   0.,   0.],
       [  0.,   1.,   0.,   0.,   0.],
       [  0.,   0.,   2.,   0.,   0.],
       [  0.,   0.,   0.,   3.,   0.],
       [  0.,   0.,   0.,   0.,   0.]])

In [31]:
b

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [27]:
def iter_me(n, dict_its):
    fraction = (1,2)
    for i in range(n):
        if not dict_its.get(i):
            fraction =invert(suma(fraction,2))
            dict_its[i] = fraction
        else:
            fraction = dict_its.get(i)
            
    fraction = suma(fraction, 1)
    return fraction, dict_its

In [36]:
result, dict_its = iter_me(7,dict_its)
print(result)

(1393, 985)


In [37]:
def islonger(fraction):
    return len(str(fraction[0])) > len(str(fraction[1]))

In [47]:
st = time.time()
dict_its = {}
ct= 0
for number in range(0,1001):
    result, dict_its = iter_me(number, dict_its)
    if islonger(result):
        ct +=1
ct
end = time.time()
print(ct, end-st)

153 1.248049020767212


In [41]:
#without dict_cache:
def iter_me2(n):
    fraction = (1,2)
    for i in range(n):
        fraction =invert(suma(fraction,2))
            
    fraction = suma(fraction, 1)
    return fraction

In [45]:
st = time.time()
ct2= 0
for number in range(0,1001):
    if islonger(iter_me2(number)):
        ct2 +=1
ct2
end= time.time()
print(ct2, end-st)

153 4.801342010498047


In [44]:
import time

In [49]:

class br:
    def __init__(self, num, dem=1):
        self.num = num
        self.dem = dem

    def __mul__(self, other):
        return br(self.num*other.num, self.dem*other.dem)

    def __str__(self):
        return "%d\n---\n%d\n" % (self.num, self.dem)

    def __div__(self, other):
        return br(self.num*other.dem, self.dem*other.num)

    def __add__(self, other):
        s = self * br(other.dem)
        o = other * br(self.dem)
        return br(s.num+o.num, s.dem*o.dem)
    def numbiggerdem(self):
        return len(str(self.num)) > len(str(self.dem))
st = time.time()
b = br(1,2)
c = 0
for i in range(1001):
    if (br(1)+b).numbiggerdem():
        c+=1
        #print (br(1)+b)
    b = br(1).__div__((br(2)+b))

end = time.time()    
print(c, end-st)




153 0.2516350746154785
